# Generated by Django 3.1.2 on 2020-12-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목', max_length=64, verbose_name='제목')),
                ('description', models.CharField(blank=True, help_text='설명', max_length=256, null=True, verbose_name='설명')),
                ('author', models.CharField(help_text='작성자', max_length=16, verbose_name='작성자')),
                ('due_date', models.DateTimeField(help_text='마감일', verbose_name='마감일')),
                ('completed', models.BooleanField(default=False, help_text='완료 여부', verbose_name='완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 날짜 시간', verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 날짜 시간', verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '할일 목록',
                'verbose_name_plural': '핧일 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
